# CN105 Mitsubishi Heat Pump Package
# Import with: packages:
#   cn105: github://brianfeucht/esphome-configs/packages/cn105.yaml
substitutions:
  board_type: "lolin_s2_mini"
  uart_tx_pin: "39"
  uart_rx_pin: "40"
  status_led_pin: "15"
  climate_update_interval: "1.5s"

# External component for CN105
external_components:
  - source: github://brianfeucht/MitsubishiCN105ESPHome@copilot/add-native-dual-setpoint
    refresh: 1min

# Default ESP32 configuration (override in substitutions if needed)
esp32:
  board: ${board_type}
  framework:
    type: esp-idf

# UART configuration for CN105
uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}

# CN105-specific logging
logger:
  level: INFO
  logs:
    CYCLE: WARN

# Climate configuration - CN105 heat pump
climate:
  - platform: cn105
    id: hp
    name: "${friendly_name}"
    heat_cool_deadband: 1.0  # Optional: deadband in °C (default: 0.5, range: 0.0-5.0)
    heat_cool_idle_fan_time: 5min  # Optional: fan run time (default: 5min)
    supports:
      mode: [HEAT, COOL, HEAT_COOL]
    update_interval: ${climate_update_interval}
    fahrenheit_compatibility: true
    vertical_vane_select:
      name: "${friendly_name} Vertical Vane"
      disabled_by_default: false
    horizontal_vane_select:
      name: "${friendly_name} Horizontal Vane"
      disabled_by_default: false
    stage_sensor:
      name: "${friendly_name} Stage"
      entity_category: diagnostic
      disabled_by_default: false
    sub_mode_sensor:
      name: "${friendly_name} Sub Mode"
      entity_category: diagnostic
      disabled_by_default: false
    auto_sub_mode_sensor:
      name: "${friendly_name} Auto Sub Mode"
      entity_category: diagnostic
      disabled_by_default: false
