# Example Smart Switch/Relay Controller
# Basic relay control with physical button

substitutions:
  devicename: "switch-garage"
  friendly_name: "Garage Switch"
  board_type: "esp32dev"
  status_led_pin: "2"
  
  # Switch configuration
  relay_pin: "12"
  button_pin: "0"

# Include base functionality
<<: !include ../../templates/common/base.yaml

# Define the physical switch
switch:
  - platform: gpio
    pin: ${relay_pin}
    name: "${friendly_name}"
    id: relay

# Define physical button
binary_sensor:
  - platform: gpio
    pin:
      number: ${button_pin}
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay