# Meta Thermostat Configuration
# Provides dual setpoint functionality with separate heating/cooling setpoints

- platform: thermostat
  id: meta_thermostat
  name: "${friendly_name} Thermostat"
  
  # Use remote temperature sensor from Home Assistant
  sensor: ${remote_temp_sensor}
  humidity_sensor: ${remote_humid_sensor}
  
  # Heating configuration
  heat_action:
    - climate.control:
        id: hp
        mode: HEAT
  heat_deadband: 0.5 °C
  heat_overrun: 0.5 °C
  
  # Cooling configuration  
  cool_action:
    - climate.control:
        id: hp
        mode: COOL
  cool_deadband: 0.5 °C
  cool_overrun: 0.5 °C
  
  # Idle action (turn off heat pump)
  idle_action:
    - climate.control:
        id: hp
        mode: "OFF"
  
  # Default settings
  default_preset: Home
  away_config:
    default_target_temperature_low: 16 °C
    default_target_temperature_high: 26 °C
  
  # Temperature limits
  min_cooling_off_time: 300s
  min_cooling_run_time: 300s
  min_heating_off_time: 300s  
  min_heating_run_time: 300s
  min_idle_time: 30s
  
  # Presets
  preset:
    - name: Home
      default_target_temperature_low: 21 °C
      default_target_temperature_high: 24 °C
    - name: Away  
      default_target_temperature_low: 16 °C
      default_target_temperature_high: 26 °C
    - name: Sleep
      default_target_temperature_low: 19 °C
      default_target_temperature_high: 25 °C
