# Version Information Text Sensors
# Provides ESPHome and firmware version information

- platform: version
  name: ESPHome Version
  entity_category: diagnostic

- platform: template
  name: Uptime Human Readable
  id: uptime_human
  icon: mdi:clock-start
  entity_category: diagnostic
