# WiFi Status Text Sensors
# Provides WiFi connection information

- platform: wifi_info
  ip_address:
    name: IP Address
    entity_category: diagnostic
  ssid:
    name: Connected SSID
    entity_category: diagnostic
  bssid:
    name: Connected BSSID
    entity_category: diagnostic
  mac_address:
    name: Mac Address
    entity_category: diagnostic
  scan_results:
    name: Latest Scan Results
    entity_category: diagnostic
