# HVAC Master Closet - Import into ESPHome
# No copying needed - imports directly from GitHub!

substitutions:
  # Device identification
  devicename: "hvac-mastercloset"
  friendly_name: "HVAC Master Closet"
  
  # Board configuration
  board_type: "lolin_s2_mini"
  
  # CN105 pins
  uart_tx_pin: "39"
  uart_rx_pin: "40"
  
  # Status LED
  status_led_pin: "15"
  
  # Update intervals
  climate_update_interval: "1.5s"

# Import packages from GitHub
packages:
  esphome_base: github://brianfeucht/esphome-configs/packages/base.yaml
  cn105: github://brianfeucht/esphome-configs/packages/cn105.yaml