# ESPHome Base Package
# Import with: packages:
#   esphome_base: github://brianfeucht/esphome-configs/packages/base.yaml
substitutions:
  friendly_name: ${devicename}

# Core ESPHome configuration
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Web server for device management
web_server:
  port: 80
  ota: false

# Status LED (if pin defined)
status_led:
  pin: ${status_led_pin}

# Time synchronization with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Basic diagnostic sensors
sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    entity_category: diagnostic

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
