# DHT Environmental Sensor Package
# Import with: packages:
#   dht_sensor: github://brianfeucht/esphome-configs/packages/dht-sensor.yaml

# DHT Temperature and Humidity Sensor
sensor:
  - platform: dht
    pin: ${sensor_pin}
    temperature:
      name: "${friendly_name} Temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
      accuracy_decimals: 1
    humidity:
      name: "${friendly_name} Humidity"
      unit_of_measurement: "%"
      device_class: humidity
      state_class: measurement
      accuracy_decimals: 1
    update_interval: ${sensor_update_interval}